(function () {
    'use strict';
    
    angular.module('Patient')
        .factory('MessageAPI',['$http', 'ApiAdress', function ($http, ApiAdress) {
            return {
                listPatientMessage: function (patientId) {
                    return $http.get(ApiAdress + '/message/' + patientId + '/all');    
                },
                sendMessageToPatient: function (message) {
                   return  $http.post(ApiAdress + '/message/send', message); 
                }
            }
        }])
        .controller('CommunicationController', ['$scope', '$routeParams', 'MessageAPI', function ($scope, $routeParams, MessageAPI) {
            $scope.dataLoading = true;

            $scope.$parent.$watch('patient', function (newVal, oldVal) {
                if (undefined === $scope.$parent || null === $scope.$parent ||
                        undefined === $scope.$parent.patient || null === $scope.$parent.patient) {
                    return;
                }
                $scope.messageTypes = [];

                if ('' !== $scope.$parent.patient.email && null !== $scope.$parent.patient.email) {
                    $scope.messageTypes.push({
                        name: 'Email: ' + $scope.$parent.patient.email,
                        id: 1
                    });
                }
                if ('' !== $scope.$parent.patient.phone && null !== $scope.$parent.patient.phone) {
                    $scope.messageTypes.push({
                        name: 'Sms: ' + $scope.$parent.patient.phone,
                        id: 2
                    });
                }

                $scope.dataLoading = false;
                $scope.messageType = $scope.messageTypes[0];
            });

            MessageAPI.listPatientMessage( $routeParams.patientId).success(function (data) {
                $scope.dataLoading = false;
                $scope.messageList = data;
            }).error(function () {

            });
             
            $scope.ShowMessageDetails = function (messageId) {
                var message = $scope.messageList.filter(function (v) {
                    return v.messageid === messageId;
                })[0];
                if(message === undefined){
                    return;
                }
                $scope.selectedMessage.Type = message.messagetype == 0 ? 'SMS' : 'Email';
            };
            $scope.Clear = function () {
                $scope.body   = null;
                $scope.header = null;
            };
            
            $scope.Send = function () {
                $scope.dataLoading = true;
                $scope.error = null;
                MessageAPI.sendMessageToPatient(
                    {
                        sender:{
//                            personId:
                            
                        },
                        recipment:{
//                            personId:
                        },
                        messageType: $scope.messageType.id,
                        header: $scope.header,
                        body: $scope.body,
                        isAutoGenerated: false
                    }).success(function (data) {
                    $scope.header = null;
                    $scope.body = null;
                    $scope.dataLoading = false;
                }).error(function () {
                    $scope.error = 'Wystąpił błąd podczas wysyłania wiadomości';
                    $scope.dataLoading = false;
                });
            };
        }]);
}());